-- Verification Request Tracking System
-- Enables products to track verification requests and link them to on-chain transactions

-- Verification Transactions Table (ZTIZEN side)
-- Tracks all verification transactions processed by ZTIZEN
CREATE TABLE IF NOT EXISTS verification_transactions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Transaction identifier (unique for each verification)
    tx_id VARCHAR(64) UNIQUE NOT NULL,

    -- Link to product's verification request (nullable for backward compatibility)
    request_id VARCHAR(66),  -- keccak256 hash (0x + 64 hex chars)

    -- Credential reference
    credential_id UUID NOT NULL REFERENCES credentials(credential_id) ON DELETE CASCADE,

    -- Service information (from product request)
    service_id VARCHAR(255),
    service_name VARCHAR(255),
    product_id VARCHAR(255),

    -- Traditional verification results
    traditional_verified BOOLEAN NOT NULL,
    traditional_match_count INTEGER NOT NULL,
    traditional_match_rate NUMERIC(5,2) NOT NULL,

    -- ZK Proof data (nullable if ZK proof generation fails)
    zk_verified BOOLEAN,
    zk_match_count INTEGER,
    proof BYTEA,  -- ZK proof bytes
    public_inputs JSONB,  -- Public inputs as JSON array

    -- On-chain data (populated after blockchain submission)
    onchain_tx_hash VARCHAR(66),  -- Ethereum tx hash (0x + 64 hex chars)
    onchain_verified BOOLEAN,
    onchain_timestamp BIGINT,
    onchain_block_number BIGINT,

    -- Nonce tracking for replay protection
    nonce_before TEXT,
    nonce_after TEXT,

    -- Metadata
    timestamp BIGINT NOT NULL,
    ip_address VARCHAR(45),
    user_agent TEXT,

    -- Timestamps
    created_at TIMESTAMP DEFAULT NOW(),

    -- Constraints
    CONSTRAINT check_traditional_match_rate CHECK (traditional_match_rate >= 0 AND traditional_match_rate <= 100),
    CONSTRAINT check_traditional_match_count CHECK (traditional_match_count >= 0 AND traditional_match_count <= 128),
    CONSTRAINT check_zk_match_count CHECK (zk_match_count IS NULL OR (zk_match_count >= 0 AND zk_match_count <= 128))
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_verification_tx_request ON verification_transactions(request_id);
CREATE INDEX IF NOT EXISTS idx_verification_tx_credential ON verification_transactions(credential_id);
CREATE INDEX IF NOT EXISTS idx_verification_tx_service ON verification_transactions(service_id);
CREATE INDEX IF NOT EXISTS idx_verification_tx_product ON verification_transactions(product_id);
CREATE INDEX IF NOT EXISTS idx_verification_tx_onchain ON verification_transactions(onchain_tx_hash);
CREATE INDEX IF NOT EXISTS idx_verification_tx_timestamp ON verification_transactions(timestamp);
CREATE INDEX IF NOT EXISTS idx_verification_tx_created ON verification_transactions(created_at DESC);

-- Composite index for user's verification history
CREATE INDEX IF NOT EXISTS idx_verification_tx_credential_timestamp ON verification_transactions(credential_id, timestamp DESC);

-- Comments for documentation
COMMENT ON TABLE verification_transactions IS 'Tracks all verification transactions with traditional, ZK proof, and on-chain data';
COMMENT ON COLUMN verification_transactions.tx_id IS 'Unique transaction ID generated by ZTIZEN';
COMMENT ON COLUMN verification_transactions.request_id IS 'Links to product verification request (keccak256 hash)';
COMMENT ON COLUMN verification_transactions.traditional_verified IS 'Whether traditional off-chain verification passed (89.8% threshold)';
COMMENT ON COLUMN verification_transactions.zk_verified IS 'Whether ZK proof verification passed (85.2% threshold, 109/128 bits)';
COMMENT ON COLUMN verification_transactions.proof IS 'ZK proof bytes (UltraHonk proof)';
COMMENT ON COLUMN verification_transactions.public_inputs IS 'ZK proof public inputs (match count, etc.)';
COMMENT ON COLUMN verification_transactions.onchain_tx_hash IS 'Ethereum transaction hash after on-chain submission';
COMMENT ON COLUMN verification_transactions.nonce_before IS 'Nonce value before verification (for audit trail)';
COMMENT ON COLUMN verification_transactions.nonce_after IS 'Nonce value after successful verification (rolled nonce)';
