/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LfwExtractRouteImport } from './routes/lfw-extract'
import { Route as FacescrubExtractRouteImport } from './routes/facescrub-extract'
import { Route as CollectRouteImport } from './routes/collect'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIndexRouteImport } from './routes/product.index'
import { Route as ZtizenVerifyRouteImport } from './routes/ztizen.verify'
import { Route as ZtizenMeRouteImport } from './routes/ztizen.me'
import { Route as ProductVerifyDemoRouteImport } from './routes/product.verify-demo'
import { Route as ZtizenVerifyCredentialIdRouteImport } from './routes/ztizen.verify.$credentialId'
import { Route as ZtizenVerifyZkCredentialIdRouteImport } from './routes/ztizen.verify-zk.$credentialId'
import { Route as ZtizenVerifyStagedCredentialIdRouteImport } from './routes/ztizen.verify-staged.$credentialId'
import { Route as ZtizenRegisterCredentialIdRouteImport } from './routes/ztizen.register.$credentialId'
import { Route as ZtizenRegisterScanCredentialIdRouteImport } from './routes/ztizen.register-scan.$credentialId'
import { Route as ZtizenMeAddCredentialIdRouteImport } from './routes/ztizen.me-add.$credentialId'
import { Route as ProductServiceServiceNameRouteImport } from './routes/product.service.$serviceName'

const LfwExtractRoute = LfwExtractRouteImport.update({
  id: '/lfw-extract',
  path: '/lfw-extract',
  getParentRoute: () => rootRouteImport,
} as any)
const FacescrubExtractRoute = FacescrubExtractRouteImport.update({
  id: '/facescrub-extract',
  path: '/facescrub-extract',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectRoute = CollectRouteImport.update({
  id: '/collect',
  path: '/collect',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIndexRoute = ProductIndexRouteImport.update({
  id: '/product/',
  path: '/product/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZtizenVerifyRoute = ZtizenVerifyRouteImport.update({
  id: '/ztizen/verify',
  path: '/ztizen/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ZtizenMeRoute = ZtizenMeRouteImport.update({
  id: '/ztizen/me',
  path: '/ztizen/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductVerifyDemoRoute = ProductVerifyDemoRouteImport.update({
  id: '/product/verify-demo',
  path: '/product/verify-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ZtizenVerifyCredentialIdRoute =
  ZtizenVerifyCredentialIdRouteImport.update({
    id: '/$credentialId',
    path: '/$credentialId',
    getParentRoute: () => ZtizenVerifyRoute,
  } as any)
const ZtizenVerifyZkCredentialIdRoute =
  ZtizenVerifyZkCredentialIdRouteImport.update({
    id: '/ztizen/verify-zk/$credentialId',
    path: '/ztizen/verify-zk/$credentialId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ZtizenVerifyStagedCredentialIdRoute =
  ZtizenVerifyStagedCredentialIdRouteImport.update({
    id: '/ztizen/verify-staged/$credentialId',
    path: '/ztizen/verify-staged/$credentialId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ZtizenRegisterCredentialIdRoute =
  ZtizenRegisterCredentialIdRouteImport.update({
    id: '/ztizen/register/$credentialId',
    path: '/ztizen/register/$credentialId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ZtizenRegisterScanCredentialIdRoute =
  ZtizenRegisterScanCredentialIdRouteImport.update({
    id: '/ztizen/register-scan/$credentialId',
    path: '/ztizen/register-scan/$credentialId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ZtizenMeAddCredentialIdRoute = ZtizenMeAddCredentialIdRouteImport.update({
  id: '/ztizen/me-add/$credentialId',
  path: '/ztizen/me-add/$credentialId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductServiceServiceNameRoute =
  ProductServiceServiceNameRouteImport.update({
    id: '/product/service/$serviceName',
    path: '/product/service/$serviceName',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collect': typeof CollectRoute
  '/facescrub-extract': typeof FacescrubExtractRoute
  '/lfw-extract': typeof LfwExtractRoute
  '/product/verify-demo': typeof ProductVerifyDemoRoute
  '/ztizen/me': typeof ZtizenMeRoute
  '/ztizen/verify': typeof ZtizenVerifyRouteWithChildren
  '/product': typeof ProductIndexRoute
  '/product/service/$serviceName': typeof ProductServiceServiceNameRoute
  '/ztizen/me-add/$credentialId': typeof ZtizenMeAddCredentialIdRoute
  '/ztizen/register-scan/$credentialId': typeof ZtizenRegisterScanCredentialIdRoute
  '/ztizen/register/$credentialId': typeof ZtizenRegisterCredentialIdRoute
  '/ztizen/verify-staged/$credentialId': typeof ZtizenVerifyStagedCredentialIdRoute
  '/ztizen/verify-zk/$credentialId': typeof ZtizenVerifyZkCredentialIdRoute
  '/ztizen/verify/$credentialId': typeof ZtizenVerifyCredentialIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collect': typeof CollectRoute
  '/facescrub-extract': typeof FacescrubExtractRoute
  '/lfw-extract': typeof LfwExtractRoute
  '/product/verify-demo': typeof ProductVerifyDemoRoute
  '/ztizen/me': typeof ZtizenMeRoute
  '/ztizen/verify': typeof ZtizenVerifyRouteWithChildren
  '/product': typeof ProductIndexRoute
  '/product/service/$serviceName': typeof ProductServiceServiceNameRoute
  '/ztizen/me-add/$credentialId': typeof ZtizenMeAddCredentialIdRoute
  '/ztizen/register-scan/$credentialId': typeof ZtizenRegisterScanCredentialIdRoute
  '/ztizen/register/$credentialId': typeof ZtizenRegisterCredentialIdRoute
  '/ztizen/verify-staged/$credentialId': typeof ZtizenVerifyStagedCredentialIdRoute
  '/ztizen/verify-zk/$credentialId': typeof ZtizenVerifyZkCredentialIdRoute
  '/ztizen/verify/$credentialId': typeof ZtizenVerifyCredentialIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collect': typeof CollectRoute
  '/facescrub-extract': typeof FacescrubExtractRoute
  '/lfw-extract': typeof LfwExtractRoute
  '/product/verify-demo': typeof ProductVerifyDemoRoute
  '/ztizen/me': typeof ZtizenMeRoute
  '/ztizen/verify': typeof ZtizenVerifyRouteWithChildren
  '/product/': typeof ProductIndexRoute
  '/product/service/$serviceName': typeof ProductServiceServiceNameRoute
  '/ztizen/me-add/$credentialId': typeof ZtizenMeAddCredentialIdRoute
  '/ztizen/register-scan/$credentialId': typeof ZtizenRegisterScanCredentialIdRoute
  '/ztizen/register/$credentialId': typeof ZtizenRegisterCredentialIdRoute
  '/ztizen/verify-staged/$credentialId': typeof ZtizenVerifyStagedCredentialIdRoute
  '/ztizen/verify-zk/$credentialId': typeof ZtizenVerifyZkCredentialIdRoute
  '/ztizen/verify/$credentialId': typeof ZtizenVerifyCredentialIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collect'
    | '/facescrub-extract'
    | '/lfw-extract'
    | '/product/verify-demo'
    | '/ztizen/me'
    | '/ztizen/verify'
    | '/product'
    | '/product/service/$serviceName'
    | '/ztizen/me-add/$credentialId'
    | '/ztizen/register-scan/$credentialId'
    | '/ztizen/register/$credentialId'
    | '/ztizen/verify-staged/$credentialId'
    | '/ztizen/verify-zk/$credentialId'
    | '/ztizen/verify/$credentialId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collect'
    | '/facescrub-extract'
    | '/lfw-extract'
    | '/product/verify-demo'
    | '/ztizen/me'
    | '/ztizen/verify'
    | '/product'
    | '/product/service/$serviceName'
    | '/ztizen/me-add/$credentialId'
    | '/ztizen/register-scan/$credentialId'
    | '/ztizen/register/$credentialId'
    | '/ztizen/verify-staged/$credentialId'
    | '/ztizen/verify-zk/$credentialId'
    | '/ztizen/verify/$credentialId'
  id:
    | '__root__'
    | '/'
    | '/collect'
    | '/facescrub-extract'
    | '/lfw-extract'
    | '/product/verify-demo'
    | '/ztizen/me'
    | '/ztizen/verify'
    | '/product/'
    | '/product/service/$serviceName'
    | '/ztizen/me-add/$credentialId'
    | '/ztizen/register-scan/$credentialId'
    | '/ztizen/register/$credentialId'
    | '/ztizen/verify-staged/$credentialId'
    | '/ztizen/verify-zk/$credentialId'
    | '/ztizen/verify/$credentialId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectRoute: typeof CollectRoute
  FacescrubExtractRoute: typeof FacescrubExtractRoute
  LfwExtractRoute: typeof LfwExtractRoute
  ProductVerifyDemoRoute: typeof ProductVerifyDemoRoute
  ZtizenMeRoute: typeof ZtizenMeRoute
  ZtizenVerifyRoute: typeof ZtizenVerifyRouteWithChildren
  ProductIndexRoute: typeof ProductIndexRoute
  ProductServiceServiceNameRoute: typeof ProductServiceServiceNameRoute
  ZtizenMeAddCredentialIdRoute: typeof ZtizenMeAddCredentialIdRoute
  ZtizenRegisterScanCredentialIdRoute: typeof ZtizenRegisterScanCredentialIdRoute
  ZtizenRegisterCredentialIdRoute: typeof ZtizenRegisterCredentialIdRoute
  ZtizenVerifyStagedCredentialIdRoute: typeof ZtizenVerifyStagedCredentialIdRoute
  ZtizenVerifyZkCredentialIdRoute: typeof ZtizenVerifyZkCredentialIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lfw-extract': {
      id: '/lfw-extract'
      path: '/lfw-extract'
      fullPath: '/lfw-extract'
      preLoaderRoute: typeof LfwExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facescrub-extract': {
      id: '/facescrub-extract'
      path: '/facescrub-extract'
      fullPath: '/facescrub-extract'
      preLoaderRoute: typeof FacescrubExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collect': {
      id: '/collect'
      path: '/collect'
      fullPath: '/collect'
      preLoaderRoute: typeof CollectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/': {
      id: '/product/'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ztizen/verify': {
      id: '/ztizen/verify'
      path: '/ztizen/verify'
      fullPath: '/ztizen/verify'
      preLoaderRoute: typeof ZtizenVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ztizen/me': {
      id: '/ztizen/me'
      path: '/ztizen/me'
      fullPath: '/ztizen/me'
      preLoaderRoute: typeof ZtizenMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/verify-demo': {
      id: '/product/verify-demo'
      path: '/product/verify-demo'
      fullPath: '/product/verify-demo'
      preLoaderRoute: typeof ProductVerifyDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ztizen/verify/$credentialId': {
      id: '/ztizen/verify/$credentialId'
      path: '/$credentialId'
      fullPath: '/ztizen/verify/$credentialId'
      preLoaderRoute: typeof ZtizenVerifyCredentialIdRouteImport
      parentRoute: typeof ZtizenVerifyRoute
    }
    '/ztizen/verify-zk/$credentialId': {
      id: '/ztizen/verify-zk/$credentialId'
      path: '/ztizen/verify-zk/$credentialId'
      fullPath: '/ztizen/verify-zk/$credentialId'
      preLoaderRoute: typeof ZtizenVerifyZkCredentialIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ztizen/verify-staged/$credentialId': {
      id: '/ztizen/verify-staged/$credentialId'
      path: '/ztizen/verify-staged/$credentialId'
      fullPath: '/ztizen/verify-staged/$credentialId'
      preLoaderRoute: typeof ZtizenVerifyStagedCredentialIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ztizen/register/$credentialId': {
      id: '/ztizen/register/$credentialId'
      path: '/ztizen/register/$credentialId'
      fullPath: '/ztizen/register/$credentialId'
      preLoaderRoute: typeof ZtizenRegisterCredentialIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ztizen/register-scan/$credentialId': {
      id: '/ztizen/register-scan/$credentialId'
      path: '/ztizen/register-scan/$credentialId'
      fullPath: '/ztizen/register-scan/$credentialId'
      preLoaderRoute: typeof ZtizenRegisterScanCredentialIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ztizen/me-add/$credentialId': {
      id: '/ztizen/me-add/$credentialId'
      path: '/ztizen/me-add/$credentialId'
      fullPath: '/ztizen/me-add/$credentialId'
      preLoaderRoute: typeof ZtizenMeAddCredentialIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/service/$serviceName': {
      id: '/product/service/$serviceName'
      path: '/product/service/$serviceName'
      fullPath: '/product/service/$serviceName'
      preLoaderRoute: typeof ProductServiceServiceNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ZtizenVerifyRouteChildren {
  ZtizenVerifyCredentialIdRoute: typeof ZtizenVerifyCredentialIdRoute
}

const ZtizenVerifyRouteChildren: ZtizenVerifyRouteChildren = {
  ZtizenVerifyCredentialIdRoute: ZtizenVerifyCredentialIdRoute,
}

const ZtizenVerifyRouteWithChildren = ZtizenVerifyRoute._addFileChildren(
  ZtizenVerifyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectRoute: CollectRoute,
  FacescrubExtractRoute: FacescrubExtractRoute,
  LfwExtractRoute: LfwExtractRoute,
  ProductVerifyDemoRoute: ProductVerifyDemoRoute,
  ZtizenMeRoute: ZtizenMeRoute,
  ZtizenVerifyRoute: ZtizenVerifyRouteWithChildren,
  ProductIndexRoute: ProductIndexRoute,
  ProductServiceServiceNameRoute: ProductServiceServiceNameRoute,
  ZtizenMeAddCredentialIdRoute: ZtizenMeAddCredentialIdRoute,
  ZtizenRegisterScanCredentialIdRoute: ZtizenRegisterScanCredentialIdRoute,
  ZtizenRegisterCredentialIdRoute: ZtizenRegisterCredentialIdRoute,
  ZtizenVerifyStagedCredentialIdRoute: ZtizenVerifyStagedCredentialIdRoute,
  ZtizenVerifyZkCredentialIdRoute: ZtizenVerifyZkCredentialIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
