// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import "./interfaces/IZTIZEN.sol";

// ============ Verifier Interfaces ============

/// @dev Noir/UltraHonk verifier — generated by bb (Barretenberg)
interface INoirVerifier {
    function verify(bytes calldata _proof, bytes32[] calldata _publicInputs) external returns (bool);
}

/// @dev Circom/Groth16 verifier — generated by snarkjs
/// Proof is split into pA (G1), pB (G2), pC (G1). pubSignals = 129 values:
///   [0]       = match_count (public output from circuit)
///   [1..128]  = computed_commit[128] (public output — 128 Poseidon hashes)
interface ICircomVerifier {
    function verifyProof(
        uint256[2] calldata pA,
        uint256[2][2] calldata pB,
        uint256[2] calldata pC,
        uint256[129] calldata pubSignals
    ) external view returns (bool);
}

/**
 * @title ZTIZEN
 * @dev Trustless Biometric Authentication with ZK Proofs
 *
 * Supports dual ZK backends:
 *   - Noir/UltraHonk  (verify via INoirVerifier)
 *   - Circom/Groth16  (verify via ICircomVerifier)
 *
 * Auth commit rotation design:
 *   - auth_commit[128] stored off-chain in ZTIZEN service DB (not on-chain — 4KB per credential)
 *   - nonce stored on-chain — rolls after every successful verification
 *   - Each login: user recomputes Poseidon(bits, nonce_N, keys) and proves against stored commit_N
 *   - After success: contract advances nonce_N → nonce_{N+1} on-chain
 *                    service DB rotates commit_N → commit_{N+1} (baked with nonce_{N+1})
 *
 * Storage (4 mappings):
 *   credentialServiceNonces  — nonce per (credentialId, serviceId)
 *   _credentials             — credential metadata
 *   _ownerCredentials        — owner → credentialIds index
 *   whitelistedUsers         — enrollment whitelist
 */
contract ZTIZEN is Ownable, ReentrancyGuard, IZTIZEN {

    // ============ Types ============

    enum VerifierType { Noir, Circom }

    // ============ Storage ============

    /// @dev credential -> service -> current nonce (anti-replay anchor)
    mapping(bytes32 => mapping(bytes32 => uint256)) public credentialServiceNonces;

    /// @dev credentialId -> CredentialMeta
    mapping(bytes32 => IZTIZENCore.CredentialMeta) private _credentials;

    /// @dev owner -> credentialIds[]
    mapping(address => bytes32[]) private _ownerCredentials;

    /// @dev user -> whitelisted for enrollment
    mapping(address => bool) public whitelistedUsers;

    uint256 public totalCredentials;
    bool public zkVerificationEnabled;

    INoirVerifier public noirVerifier;
    ICircomVerifier public circomVerifier;

    // Active backend — owner can switch between Noir and Circom
    VerifierType public activeVerifier;

    // ============ Events ============

    event CredentialRegistered(bytes32 indexed credentialId, address indexed owner, uint256 version, uint256 timestamp);
    event CredentialActivatedForService(bytes32 indexed credentialId, bytes32 indexed serviceId, uint256 initialNonce, uint256 timestamp);
    event CredentialDeactivated(bytes32 indexed credentialId, address indexed owner, uint256 timestamp);
    event CredentialReactivated(bytes32 indexed credentialId, address indexed owner, uint256 timestamp);

    event ProofVerified(
        bytes32 indexed credentialId,
        bytes32 indexed serviceId,
        bytes32 indexed productTxId,
        address caller,
        VerifierType verifierUsed,
        uint256 oldNonce,
        uint256 newNonce,
        uint256 timestamp
    );

    event NonceRevoked(bytes32 indexed credentialId, bytes32 indexed serviceId, uint256 oldNonce, uint256 newNonce, uint256 timestamp);
    event UserWhitelisted(address indexed userAddress);
    event UserRemovedFromWhitelist(address indexed userAddress);
    event ZKVerificationEnabledChanged(bool enabled);
    event NoirVerifierChanged(address newVerifier);
    event CircomVerifierChanged(address newVerifier);
    event ActiveVerifierChanged(VerifierType verifierType);

    // ============ Modifiers ============

    modifier onlyCredentialOwner(bytes32 _credentialId) {
        require(_credentials[_credentialId].owner == msg.sender, "ZTIZEN: Not credential owner");
        _;
    }

    modifier credentialMustExist(bytes32 _credentialId) {
        require(_credentials[_credentialId].owner != address(0), "ZTIZEN: Credential does not exist");
        _;
    }

    modifier credentialMustBeActive(bytes32 _credentialId) {
        require(_credentials[_credentialId].isActive, "ZTIZEN: Credential is not active");
        _;
    }

    modifier onlyWhitelisted(address _user) {
        require(whitelistedUsers[_user], "ZTIZEN: User not whitelisted");
        _;
    }

    // ============ Constructor ============

    constructor(address _noirVerifier, address _circomVerifier) Ownable(msg.sender) {
        zkVerificationEnabled = false;
        activeVerifier = VerifierType.Noir;

        if (_noirVerifier != address(0)) {
            noirVerifier = INoirVerifier(_noirVerifier);
        }
        if (_circomVerifier != address(0)) {
            circomVerifier = ICircomVerifier(_circomVerifier);
        }
    }

    // ============ IZTIZENCore — Credential Registration ============

    function registerCredential(
        bytes32 credentialId,
        address userAddress,
        uint256 version
    ) external override onlyOwner onlyWhitelisted(userAddress) nonReentrant returns (bool) {
        require(_credentials[credentialId].owner == address(0), "ZTIZEN: Credential already exists");
        require(version > 0, "ZTIZEN: Invalid version");

        _credentials[credentialId] = IZTIZENCore.CredentialMeta({
            owner: userAddress,
            version: version,
            isActive: true,
            registeredAt: block.timestamp,
            lastVerifiedAt: 0
        });

        _ownerCredentials[userAddress].push(credentialId);
        totalCredentials++;

        emit CredentialRegistered(credentialId, userAddress, version, block.timestamp);
        return true;
    }

    function initializeCredentialForService(
        bytes32 credentialId,
        bytes32 serviceId,
        uint256 initialNonce
    ) external override onlyOwner credentialMustExist(credentialId) credentialMustBeActive(credentialId) nonReentrant returns (bool) {
        require(credentialServiceNonces[credentialId][serviceId] == 0, "ZTIZEN: Already initialized");
        require(initialNonce > 0, "ZTIZEN: Initial nonce must be non-zero");

        credentialServiceNonces[credentialId][serviceId] = initialNonce;
        emit CredentialActivatedForService(credentialId, serviceId, initialNonce, block.timestamp);
        return true;
    }

    // ============ IZTIZENCore — Credential Management ============

    function deactivateCredential(bytes32 credentialId)
        external override nonReentrant onlyCredentialOwner(credentialId) credentialMustExist(credentialId)
        returns (bool)
    {
        require(_credentials[credentialId].isActive, "ZTIZEN: Already deactivated");
        _credentials[credentialId].isActive = false;
        emit CredentialDeactivated(credentialId, msg.sender, block.timestamp);
        return true;
    }

    function reactivateCredential(bytes32 credentialId)
        external override nonReentrant onlyCredentialOwner(credentialId) credentialMustExist(credentialId)
        returns (bool)
    {
        require(!_credentials[credentialId].isActive, "ZTIZEN: Already active");
        _credentials[credentialId].isActive = true;
        emit CredentialReactivated(credentialId, msg.sender, block.timestamp);
        return true;
    }

    // ============ IZTIZENCore — Queries ============

    function credentialExists(bytes32 credentialId) external view override returns (bool) {
        return _credentials[credentialId].owner != address(0);
    }

    function isCredentialActive(bytes32 credentialId) external view override returns (bool) {
        return _credentials[credentialId].isActive;
    }

    function getCredentialOwner(bytes32 credentialId) external view override returns (address) {
        return _credentials[credentialId].owner;
    }

    function getCredential(bytes32 credentialId)
        external view override credentialMustExist(credentialId)
        returns (IZTIZENCore.CredentialMeta memory)
    {
        return _credentials[credentialId];
    }

    function getOwnerCredentials(address owner) external view override returns (bytes32[] memory) {
        return _ownerCredentials[owner];
    }

    // ============ IZTIZENCore — Whitelist ============

    function addWhitelistedUser(address userAddress) external override onlyOwner {
        require(userAddress != address(0), "ZTIZEN: Invalid address");
        whitelistedUsers[userAddress] = true;
        emit UserWhitelisted(userAddress);
    }

    function removeWhitelistedUser(address userAddress) external override onlyOwner {
        whitelistedUsers[userAddress] = false;
        emit UserRemovedFromWhitelist(userAddress);
    }

    function isUserWhitelisted(address userAddress) external view override returns (bool) {
        return whitelistedUsers[userAddress];
    }

    // ============ IZTIZENVerifier — ZK Proof Verification ============

    /**
     * @dev Verify a ZK biometric proof and roll the nonce.
     *
     * Uses whichever backend is currently set as `activeVerifier`.
     *
     * Noir proof format (bytes calldata proof):
     *   Raw UltraHonk proof bytes as output by aztec bb.js
     *   publicInputs: bytes32[] of 273 values (match_count + computed_commit[128] + padding)
     *
     * Circom proof format (bytes calldata proof):
     *   ABI-encoded (uint256[2] pA, uint256[2][2] pB, uint256[2] pC)
     *   publicInputs: bytes32[] of 129 values — [0]=match_count, [1..128]=computed_commit[128]
     *   (decoded internally and forwarded to ICircomVerifier.verifyProof)
     *
     * On success:
     *   - nonce advances on-chain (prevents proof replay)
     *   - caller's service should update off-chain auth_commit using the new nonce
     */
    function verifyProof(
        bytes32 credentialId,
        bytes32 serviceId,
        uint256 currentNonce,
        bytes32 productTxId,
        bytes calldata proof,
        bytes32[] calldata publicInputs
    )
        external
        override
        nonReentrant
        credentialMustExist(credentialId)
        credentialMustBeActive(credentialId)
        returns (bool success, uint256 newNonce)
    {
        require(zkVerificationEnabled, "ZTIZEN: ZK verification not enabled");

        // Validate nonce matches on-chain state — replay guard
        uint256 storedNonce = credentialServiceNonces[credentialId][serviceId];
        require(storedNonce != 0, "ZTIZEN: Credential not initialized for service");
        require(currentNonce == storedNonce, "ZTIZEN: Invalid nonce");

        // Dispatch to active verifier backend
        VerifierType usedVerifier = activeVerifier;
        if (usedVerifier == VerifierType.Noir) {
            _verifyNoir(proof, publicInputs);
        } else {
            _verifyCircom(proof, publicInputs);
        }

        // Roll nonce on-chain — next login must use newNonce
        newNonce = _rollNonce(currentNonce);
        credentialServiceNonces[credentialId][serviceId] = newNonce;
        _credentials[credentialId].lastVerifiedAt = block.timestamp;

        _emitProofVerified(credentialId, serviceId, productTxId, usedVerifier, currentNonce, newNonce);
        return (true, newNonce);
    }

    function _emitProofVerified(
        bytes32 credentialId,
        bytes32 serviceId,
        bytes32 productTxId,
        VerifierType usedVerifier,
        uint256 oldNonce,
        uint256 newNonce
    ) private {
        emit ProofVerified(credentialId, serviceId, productTxId, msg.sender, usedVerifier, oldNonce, newNonce, block.timestamp);
    }

    // ============ IZTIZENVerifier — Nonce Management ============

    function getNonce(bytes32 credentialId, bytes32 serviceId) external view override returns (uint256) {
        return credentialServiceNonces[credentialId][serviceId];
    }

    function isCredentialInitializedForService(bytes32 credentialId, bytes32 serviceId) external view override returns (bool) {
        return credentialServiceNonces[credentialId][serviceId] != 0;
    }

    /**
     * @dev Manual nonce revocation by credential owner.
     * Forces the off-chain auth_commit to be invalidated — user must re-enroll.
     * Use when a session is suspected compromised.
     */
    function revokeNonce(bytes32 credentialId, bytes32 serviceId)
        external
        override
        nonReentrant
        onlyCredentialOwner(credentialId)
        credentialMustExist(credentialId)
        returns (uint256 newNonce)
    {
        uint256 oldNonce = credentialServiceNonces[credentialId][serviceId];
        require(oldNonce != 0, "ZTIZEN: Credential not initialized for service");

        newNonce = _rollNonce(oldNonce);
        credentialServiceNonces[credentialId][serviceId] = newNonce;

        emit NonceRevoked(credentialId, serviceId, oldNonce, newNonce, block.timestamp);
        return newNonce;
    }

    // ============ IZTIZENAdmin — Configuration ============

    function setNoirVerifier(address verifierAddress) external onlyOwner {
        require(verifierAddress != address(0), "ZTIZEN: Invalid address");
        noirVerifier = INoirVerifier(verifierAddress);
        emit NoirVerifierChanged(verifierAddress);
    }

    function setCircomVerifier(address verifierAddress) external onlyOwner {
        require(verifierAddress != address(0), "ZTIZEN: Invalid address");
        circomVerifier = ICircomVerifier(verifierAddress);
        emit CircomVerifierChanged(verifierAddress);
    }

    function setActiveVerifier(VerifierType verifierType) external onlyOwner {
        if (verifierType == VerifierType.Noir) {
            require(address(noirVerifier) != address(0), "ZTIZEN: Noir verifier not set");
        } else {
            require(address(circomVerifier) != address(0), "ZTIZEN: Circom verifier not set");
        }
        activeVerifier = verifierType;
        emit ActiveVerifierChanged(verifierType);
    }

    function setZKVerificationEnabled(bool enabled) external override onlyOwner {
        zkVerificationEnabled = enabled;
        emit ZKVerificationEnabledChanged(enabled);
    }

    // Kept for interface compatibility — sets Noir verifier
    function setZKVerifier(address verifierAddress) external override onlyOwner {
        require(verifierAddress != address(0), "ZTIZEN: Invalid address");
        noirVerifier = INoirVerifier(verifierAddress);
        emit NoirVerifierChanged(verifierAddress);
    }

    function getStats()
        external view override
        returns (uint256 totalCredentials_, bool zkEnabled, address verifierAddress)
    {
        address active = activeVerifier == VerifierType.Noir
            ? address(noirVerifier)
            : address(circomVerifier);
        return (totalCredentials, zkVerificationEnabled, active);
    }

    // ============ Internal — Verifier Dispatch ============

    /// @dev Forward raw proof bytes to Noir/UltraHonk verifier
    function _verifyNoir(bytes calldata proof, bytes32[] calldata publicInputs) internal {
        require(address(noirVerifier) != address(0), "ZTIZEN: Noir verifier not set");
        bool valid = noirVerifier.verify(proof, publicInputs);
        require(valid, "ZTIZEN: Invalid Noir proof");
    }

    /**
     * @dev Unpack ABI-encoded proof bytes and forward to Circom/Groth16 verifier.
     *
     * Expected proof encoding:
     *   abi.encode(uint256[2] pA, uint256[2][2] pB, uint256[2] pC)
     *
     * Expected publicInputs layout (bytes32[], length 129):
     *   [0]       = match_count
     *   [1..128]  = computed_commit[0..127]
     */
    function _verifyCircom(bytes calldata proof, bytes32[] calldata publicInputs) internal view {
        require(address(circomVerifier) != address(0), "ZTIZEN: Circom verifier not set");
        require(publicInputs.length == 129, "ZTIZEN: Circom needs 129 public inputs");
        bool valid = _callCircomVerifier(proof, publicInputs);
        require(valid, "ZTIZEN: Invalid Circom proof");
    }

    /// @dev Isolated stack frame for Circom proof decoding + call (avoids stack-too-deep).
    /// Uses low-level staticcall to keep the 129-element array off the main stack frame.
    function _callCircomVerifier(
        bytes calldata proof,
        bytes32[] calldata publicInputs
    ) private view returns (bool) {
        (
            uint256[2] memory pA,
            uint256[2][2] memory pB,
            uint256[2] memory pC
        ) = abi.decode(proof, (uint256[2], uint256[2][2], uint256[2]));

        // Build pubSignals as dynamic uint[] to avoid fixed-size stack spill, then staticcall
        // selector: verifyProof(uint256[2],uint256[2][2],uint256[2],uint256[129])
        bytes memory callData = _buildCircomCallData(pA, pB, pC, publicInputs);
        (bool ok, bytes memory ret) = address(circomVerifier).staticcall(callData);
        require(ok, "ZTIZEN: Circom call failed");
        return abi.decode(ret, (bool));
    }

    /// @dev Encodes the Circom verifyProof call — separated to minimize stack usage in parent
    function _buildCircomCallData(
        uint256[2] memory pA,
        uint256[2][2] memory pB,
        uint256[2] memory pC,
        bytes32[] calldata publicInputs
    ) private pure returns (bytes memory) {
        // Convert bytes32[129] → uint256[129]
        uint256[129] memory pubSignals;
        for (uint256 i = 0; i < 129; i++) {
            pubSignals[i] = uint256(publicInputs[i]);
        }
        return abi.encodeWithSelector(
            ICircomVerifier.verifyProof.selector,
            pA, pB, pC, pubSignals
        );
    }

    // ============ Internal — Nonce Rolling ============

    /**
     * @dev Derive next nonce deterministically from current nonce + block context.
     * Unpredictable to the prover at proof-generation time (block.prevrandao not known until mined).
     */
    function _rollNonce(uint256 currentNonce) internal view returns (uint256 newNonce) {
        newNonce = uint256(
            keccak256(abi.encodePacked(currentNonce, block.timestamp, block.number, block.prevrandao))
        );
        if (newNonce == 0) newNonce = 1;
    }
}
