// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import "./interfaces/IZTIZEN.sol";

/**
 * @title IVerifier
 * @dev Interface for Noir ZK proof verifier (generated by bb)
 */
interface IVerifier {
    function verify(bytes calldata _proof, bytes32[] calldata _publicInputs) external returns (bool);
}

/**
 * @title ZTIZEN
 * @dev Trustless Biometric Authentication with ZK Proofs
 *
 * Implementation of trustless biometric authentication with:
 * - Oracle-only credential registration
 * - Permissionless ZK proof verification
 * - Multi-service nonce tracking
 * - Automatic nonce rolling for replay protection
 *
 * Storage (4 minimal mappings):
 * 1. credentialServiceNonces - nonce per credential+service
 * 2. _credentials - credential metadata
 * 3. _ownerCredentials - owner to credentials index
 * 4. whitelistedUsers - user whitelist for registration
 */
contract ZTIZEN is Ownable, ReentrancyGuard, IZTIZEN {
    // ============ Storage ============

    /// @dev credential -> service -> current nonce
    mapping(bytes32 => mapping(bytes32 => uint256)) public credentialServiceNonces;

    /// @dev credentialId -> CredentialMeta
    mapping(bytes32 => IZTIZENCore.CredentialMeta) private _credentials;

    /// @dev owner -> credentialIds[]
    mapping(address => bytes32[]) private _ownerCredentials;

    /// @dev user -> whitelisted
    mapping(address => bool) public whitelistedUsers;

    /// @dev Total registered credentials
    uint256 public totalCredentials;

    /// @dev ZK verification enabled
    bool public zkVerificationEnabled;

    /// @dev ZK Verifier contract
    IVerifier public zkVerifier;

    // ============ Events ============

    event CredentialRegistered(
        bytes32 indexed credentialId,
        address indexed owner,
        uint256 version,
        uint256 timestamp
    );

    event CredentialActivatedForService(
        bytes32 indexed credentialId,
        bytes32 indexed serviceId,
        uint256 initialNonce,
        uint256 timestamp
    );

    event CredentialDeactivated(
        bytes32 indexed credentialId,
        address indexed owner,
        uint256 timestamp
    );

    event CredentialReactivated(
        bytes32 indexed credentialId,
        address indexed owner,
        uint256 timestamp
    );

    event ProofVerified(
        bytes32 indexed credentialId,
        bytes32 indexed serviceId,
        bytes32 indexed productTxId,
        address verifier,
        uint256 oldNonce,
        uint256 newNonce,
        uint256 timestamp
    );

    event NonceRevoked(
        bytes32 indexed credentialId,
        bytes32 indexed serviceId,
        uint256 oldNonce,
        uint256 newNonce,
        uint256 timestamp
    );

    event UserWhitelisted(address indexed userAddress);
    event UserRemovedFromWhitelist(address indexed userAddress);
    event ZKVerificationEnabledChanged(bool enabled);
    event VerifierAddressChanged(address newVerifier);

    // ============ Modifiers ============

    modifier onlyCredentialOwner(bytes32 _credentialId) {
        require(
            _credentials[_credentialId].owner == msg.sender,
            "ZTIZEN: Not credential owner"
        );
        _;
    }

    modifier credentialMustExist(bytes32 _credentialId) {
        require(
            _credentials[_credentialId].owner != address(0),
            "ZTIZEN: Credential does not exist"
        );
        _;
    }

    modifier credentialMustBeActive(bytes32 _credentialId) {
        require(
            _credentials[_credentialId].isActive,
            "ZTIZEN: Credential is not active"
        );
        _;
    }

    modifier onlyWhitelisted(address _user) {
        require(whitelistedUsers[_user], "ZTIZEN: User not whitelisted");
        _;
    }

    // ============ Constructor ============

    constructor(address _zkVerifier) Ownable(msg.sender) {
        zkVerificationEnabled = false;
        if (_zkVerifier != address(0)) {
            zkVerifier = IVerifier(_zkVerifier);
        }
    }

    // ============ IZTIZENCore - Credential Registration ============

    function registerCredential(
        bytes32 credentialId,
        address userAddress,
        uint256 version
    ) external override onlyOwner onlyWhitelisted(userAddress) nonReentrant returns (bool success) {
        require(_credentials[credentialId].owner == address(0), "ZTIZEN: Credential already exists");
        require(version > 0, "ZTIZEN: Invalid version");

        _credentials[credentialId] = IZTIZENCore.CredentialMeta({
            owner: userAddress,
            version: version,
            isActive: true,
            registeredAt: block.timestamp,
            lastVerifiedAt: 0
        });

        _ownerCredentials[userAddress].push(credentialId);
        totalCredentials++;

        emit CredentialRegistered(credentialId, userAddress, version, block.timestamp);
        return true;
    }

    function initializeCredentialForService(
        bytes32 credentialId,
        bytes32 serviceId,
        uint256 initialNonce
    )
        external
        override
        onlyOwner
        credentialMustExist(credentialId)
        credentialMustBeActive(credentialId)
        nonReentrant
        returns (bool success)
    {
        require(credentialServiceNonces[credentialId][serviceId] == 0, "ZTIZEN: Already initialized");
        require(initialNonce > 0, "ZTIZEN: Initial nonce must be non-zero");

        credentialServiceNonces[credentialId][serviceId] = initialNonce;
        emit CredentialActivatedForService(credentialId, serviceId, initialNonce, block.timestamp);
        return true;
    }

    // ============ IZTIZENCore - Credential Management ============

    function deactivateCredential(bytes32 credentialId)
        external
        override
        nonReentrant
        onlyCredentialOwner(credentialId)
        credentialMustExist(credentialId)
        returns (bool success)
    {
        require(_credentials[credentialId].isActive, "ZTIZEN: Already deactivated");
        _credentials[credentialId].isActive = false;
        emit CredentialDeactivated(credentialId, msg.sender, block.timestamp);
        return true;
    }

    function reactivateCredential(bytes32 credentialId)
        external
        override
        nonReentrant
        onlyCredentialOwner(credentialId)
        credentialMustExist(credentialId)
        returns (bool success)
    {
        require(!_credentials[credentialId].isActive, "ZTIZEN: Already active");
        _credentials[credentialId].isActive = true;
        emit CredentialReactivated(credentialId, msg.sender, block.timestamp);
        return true;
    }

    // ============ IZTIZENCore - Credential Queries ============

    function credentialExists(bytes32 credentialId) external view override returns (bool exists) {
        return _credentials[credentialId].owner != address(0);
    }

    function isCredentialActive(bytes32 credentialId) external view override returns (bool active) {
        return _credentials[credentialId].isActive;
    }

    function getCredentialOwner(bytes32 credentialId) external view override returns (address owner) {
        return _credentials[credentialId].owner;
    }

    function getCredential(bytes32 credentialId)
        external
        view
        override
        credentialMustExist(credentialId)
        returns (IZTIZENCore.CredentialMeta memory metadata)
    {
        return _credentials[credentialId];
    }

    function getOwnerCredentials(address owner)
        external
        view
        override
        returns (bytes32[] memory credentialIds)
    {
        return _ownerCredentials[owner];
    }

    // ============ IZTIZENCore - Whitelist Management ============

    function addWhitelistedUser(address userAddress) external override onlyOwner {
        require(userAddress != address(0), "ZTIZEN: Invalid address");
        whitelistedUsers[userAddress] = true;
        emit UserWhitelisted(userAddress);
    }

    function removeWhitelistedUser(address userAddress) external override onlyOwner {
        whitelistedUsers[userAddress] = false;
        emit UserRemovedFromWhitelist(userAddress);
    }

    function isUserWhitelisted(address userAddress) external view override returns (bool whitelisted) {
        return whitelistedUsers[userAddress];
    }

    // ============ IZTIZENVerifier - ZK Proof Verification ============

    function verifyProof(
        bytes32 credentialId,
        bytes32 serviceId,
        uint256 currentNonce,
        bytes32 productTxId,
        bytes calldata proof,
        bytes32[] calldata publicInputs
    )
        external
        override
        nonReentrant
        credentialMustExist(credentialId)
        credentialMustBeActive(credentialId)
        returns (bool success, uint256 newNonce)
    {
        require(zkVerificationEnabled, "ZTIZEN: ZK verification not enabled");
        require(address(zkVerifier) != address(0), "ZTIZEN: Verifier not set");

        _validateProofNonce(credentialId, serviceId, currentNonce);
        _verifyZKProof(proof, publicInputs);

        newNonce = _rollNonce(currentNonce);
        _updateNonceAfterProof(credentialId, serviceId, currentNonce, productTxId, newNonce);

        return (true, newNonce);
    }

    /// @dev Validate proof nonce matches stored nonce
    function _validateProofNonce(
        bytes32 credentialId,
        bytes32 serviceId,
        uint256 currentNonce
    ) internal view {
        uint256 storedNonce = credentialServiceNonces[credentialId][serviceId];
        require(storedNonce != 0, "ZTIZEN: Credential not initialized for service");
        require(currentNonce == storedNonce, "ZTIZEN: Invalid nonce");
    }

    /// @dev Verify ZK proof with verifier contract
    function _verifyZKProof(
        bytes calldata proof,
        bytes32[] calldata publicInputs
    ) internal {
        bool proofValid = zkVerifier.verify(proof, publicInputs);
        require(proofValid, "ZTIZEN: Invalid ZK proof");
    }

    /// @dev Update storage after successful proof verification
    function _updateNonceAfterProof(
        bytes32 credentialId,
        bytes32 serviceId,
        uint256 oldNonce,
        bytes32 productTxId,
        uint256 newNonce
    ) internal {
        credentialServiceNonces[credentialId][serviceId] = newNonce;
        _credentials[credentialId].lastVerifiedAt = block.timestamp;
        emit ProofVerified(credentialId, serviceId, productTxId, msg.sender, oldNonce, newNonce, block.timestamp);
    }

    // ============ IZTIZENVerifier - Nonce Management ============

    function getNonce(bytes32 credentialId, bytes32 serviceId)
        external
        view
        override
        returns (uint256 nonce)
    {
        return credentialServiceNonces[credentialId][serviceId];
    }

    function isCredentialInitializedForService(bytes32 credentialId, bytes32 serviceId)
        external
        view
        override
        returns (bool initialized)
    {
        return credentialServiceNonces[credentialId][serviceId] != 0;
    }

    function revokeNonce(bytes32 credentialId, bytes32 serviceId)
        external
        override
        nonReentrant
        onlyCredentialOwner(credentialId)
        credentialMustExist(credentialId)
        returns (uint256 newNonce)
    {
        uint256 oldNonce = credentialServiceNonces[credentialId][serviceId];
        require(oldNonce != 0, "ZTIZEN: Credential not initialized for service");

        newNonce = _rollNonce(oldNonce);
        credentialServiceNonces[credentialId][serviceId] = newNonce;

        emit NonceRevoked(credentialId, serviceId, oldNonce, newNonce, block.timestamp);
        return newNonce;
    }

    // ============ IZTIZENAdmin - Configuration ============

    function setZKVerifier(address verifierAddress) external override onlyOwner {
        require(verifierAddress != address(0), "ZTIZEN: Invalid verifier address");
        zkVerifier = IVerifier(verifierAddress);
        emit VerifierAddressChanged(verifierAddress);
    }

    function setZKVerificationEnabled(bool enabled) external override onlyOwner {
        zkVerificationEnabled = enabled;
        emit ZKVerificationEnabledChanged(enabled);
    }

    function getStats()
        external
        view
        override
        returns (uint256 totalCredentials_, bool zkEnabled, address verifierAddress)
    {
        return (totalCredentials, zkVerificationEnabled, address(zkVerifier));
    }

    // ============ Internal Functions ============

    /// @dev Roll nonce deterministically but unpredictably
    function _rollNonce(uint256 currentNonce) internal view returns (uint256 newNonce) {
        newNonce = uint256(
            keccak256(abi.encodePacked(currentNonce, block.timestamp, block.number, block.prevrandao))
        );
        if (newNonce == 0) newNonce = 1;
    }
}
