-- Product Service Database Schema
-- Stores product credentials with partial keys and service details

-- Products table (registered business providers)
CREATE TABLE IF NOT EXISTS products (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Human-readable product identifier (e.g., "demo-bank")
    product_id VARCHAR(100) NOT NULL UNIQUE,

    product_name VARCHAR(255) NOT NULL,
    product_description TEXT,

    -- Partial key for this product (32 bytes as hex string)
    product_partial_key VARCHAR(64) NOT NULL UNIQUE,

    -- Product metadata
    api_endpoint VARCHAR(500),
    contact_email VARCHAR(255),
    is_active BOOLEAN DEFAULT TRUE,

    -- Timestamps
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),

    -- Constraints
    CONSTRAINT product_name_not_empty CHECK (length(product_name) > 0),
    CONSTRAINT product_id_not_empty CHECK (length(product_id) > 0)
);

-- Product Services table (specific services within a product)
-- Example: Product "MyBank" can have services "Login", "Transfer Money", "View Balance"
CREATE TABLE IF NOT EXISTS product_services (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,

    -- Service details
    service_name VARCHAR(255) NOT NULL,
    service_description TEXT,
    service_type VARCHAR(100), -- 'authentication', 'transaction', 'authorization', etc.

    -- Service-specific settings
    requires_2fa BOOLEAN DEFAULT FALSE,
    max_attempts INTEGER DEFAULT 3,
    session_timeout_minutes INTEGER DEFAULT 30,

    is_active BOOLEAN DEFAULT TRUE,

    -- Timestamps
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),

    -- Constraints
    CONSTRAINT service_name_not_empty CHECK (length(service_name) > 0),
    CONSTRAINT unique_product_service UNIQUE (product_id, service_name)
);

-- User Credentials (links users to their ZTIZEN credentials)
CREATE TABLE IF NOT EXISTS user_credentials (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    service_id UUID REFERENCES product_services(id) ON DELETE SET NULL,

    -- User identification
    user_id VARCHAR(255) NOT NULL, -- Wallet address or user ID
    credential_id UUID NOT NULL,   -- ZTIZEN credential ID

    -- Product partial key (32 bytes hex)
    product_partial_key VARCHAR(64) NOT NULL,

    -- Status
    status VARCHAR(20) DEFAULT 'pending', -- 'pending', 'enrolled', 'active', 'revoked'

    -- Timestamps
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),

    -- Constraints
    CONSTRAINT unique_user_product_service UNIQUE (user_id, product_id, service_id)
);

-- User sessions (track active authentication sessions)
CREATE TABLE IF NOT EXISTS user_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    service_id UUID REFERENCES product_services(id) ON DELETE SET NULL,

    -- User identification
    user_id VARCHAR(255) NOT NULL, -- from external system
    credential_id UUID, -- ZTIZEN credential ID

    -- Session details
    session_token VARCHAR(255) NOT NULL UNIQUE,
    ip_address INET,
    user_agent TEXT,

    -- Status
    is_active BOOLEAN DEFAULT TRUE,
    expires_at TIMESTAMP NOT NULL,

    -- Timestamps
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- Authentication logs (audit trail)
CREATE TABLE IF NOT EXISTS auth_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    service_id UUID REFERENCES product_services(id) ON DELETE SET NULL,

    -- Authentication details
    user_id VARCHAR(255),
    credential_id UUID,
    action VARCHAR(50) NOT NULL, -- 'login', 'logout', 'failed_attempt', etc.
    success BOOLEAN NOT NULL,

    -- Context
    ip_address INET,
    user_agent TEXT,
    error_message TEXT,

    timestamp TIMESTAMP DEFAULT NOW()
);

-- Verification Requests (tracks verification requests from products to ZTIZEN)
-- Product creates tx_hash = keccak256(service_id + timestamp + details)
-- This allows product to match on-chain events to their original requests
CREATE TABLE IF NOT EXISTS verification_requests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Request identifier (generated by product)
    request_id VARCHAR(100) NOT NULL UNIQUE,

    -- Product and service
    product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    service_id UUID REFERENCES product_services(id) ON DELETE SET NULL,
    service_name VARCHAR(255) NOT NULL,

    -- User and credential
    user_id VARCHAR(255) NOT NULL,
    credential_id UUID NOT NULL,

    -- Product's tx_hash for on-chain matching
    -- tx_hash = keccak256(service_id || timestamp || details)
    tx_hash VARCHAR(66), -- 0x + 64 hex chars

    -- Request details (JSON: amount, description, metadata)
    details JSONB DEFAULT '{}',

    -- Callback and return URLs
    callback_url VARCHAR(500),
    return_url VARCHAR(500),

    -- Status: pending, completed, failed, expired
    status VARCHAR(20) DEFAULT 'pending',
    verified BOOLEAN,

    -- Verification results (populated after verification)
    ztizen_tx_id UUID, -- ZTIZEN's internal transaction ID
    traditional_match_rate DECIMAL(5,4), -- e.g., 0.8523
    zk_verified BOOLEAN,
    onchain_tx_hash VARCHAR(66), -- Blockchain transaction hash

    -- Timing
    timestamp BIGINT, -- Unix timestamp when request was created
    expires_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,

    -- Timestamps
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_products_active ON products(is_active);
CREATE INDEX IF NOT EXISTS idx_product_services_product_id ON product_services(product_id);
CREATE INDEX IF NOT EXISTS idx_product_services_active ON product_services(is_active);
CREATE INDEX IF NOT EXISTS idx_user_credentials_user_id ON user_credentials(user_id);
CREATE INDEX IF NOT EXISTS idx_user_credentials_credential_id ON user_credentials(credential_id);
CREATE INDEX IF NOT EXISTS idx_user_credentials_product_id ON user_credentials(product_id);
CREATE INDEX IF NOT EXISTS idx_user_credentials_status ON user_credentials(status);
CREATE INDEX IF NOT EXISTS idx_user_sessions_product_id ON user_sessions(product_id);
CREATE INDEX IF NOT EXISTS idx_user_sessions_user_id ON user_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_user_sessions_active ON user_sessions(is_active);
CREATE INDEX IF NOT EXISTS idx_user_sessions_expires_at ON user_sessions(expires_at);
CREATE INDEX IF NOT EXISTS idx_auth_logs_product_id ON auth_logs(product_id);
CREATE INDEX IF NOT EXISTS idx_auth_logs_user_id ON auth_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_auth_logs_timestamp ON auth_logs(timestamp);
CREATE INDEX IF NOT EXISTS idx_verification_requests_request_id ON verification_requests(request_id);
CREATE INDEX IF NOT EXISTS idx_verification_requests_product_id ON verification_requests(product_id);
CREATE INDEX IF NOT EXISTS idx_verification_requests_user_id ON verification_requests(user_id);
CREATE INDEX IF NOT EXISTS idx_verification_requests_credential_id ON verification_requests(credential_id);
CREATE INDEX IF NOT EXISTS idx_verification_requests_status ON verification_requests(status);
CREATE INDEX IF NOT EXISTS idx_verification_requests_tx_hash ON verification_requests(tx_hash);
CREATE INDEX IF NOT EXISTS idx_verification_requests_onchain_tx_hash ON verification_requests(onchain_tx_hash);

-- Updated at trigger function
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Triggers for updated_at
CREATE TRIGGER update_products_updated_at BEFORE UPDATE ON products
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_product_services_updated_at BEFORE UPDATE ON product_services
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_user_credentials_updated_at BEFORE UPDATE ON user_credentials
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_user_sessions_updated_at BEFORE UPDATE ON user_sessions
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_verification_requests_updated_at BEFORE UPDATE ON verification_requests
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
